# Generated by Django 5.2.15 on 2026-06-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gearbox',
            options={'verbose_name_plural': 'Geraboxes'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
    ]
