# Generated by Django 5.2.16 on 2026-09-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_api', '0002_alter_gearbox_options_alter_status_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Make',
            new_name='Maker',
        ),
    ]
