# Generated by Django 5.2.16 on 2026-09-28 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_api', '0003_rename_make_maker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_path',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='m_motors/vehicles/'),
            preserve_default=False,
        ),
    ]
